services:
  nginx:
    build:
      context: ./docker
      dockerfile: nginx/Dockerfile
    ports:
      - "81:80"
      - "444:443"
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./docker
      dockerfile: php-fpm/Dockerfile
    user: "1000:1000"
    volumes:
      - ./:/app
      - ./docker/php/conf.d/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - postgres

  php-cli:
    build:
      context: ./docker
      dockerfile: php-cli/Dockerfile
    volumes:
      - ./:/app
      - ./docker/php/conf.d/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - postgres

  postgres:
    image: postgres:14.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cloud
    volumes:
      - simple-cloud:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mailer:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  simple-cloud:
